// <auto-generated />
using DeepSea;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

namespace DeepSea.Migrations
{
    [DbContext(typeof(DeepSeaContext))]
    [Migration("20190615042603_AddedCreatureTable")]
    partial class AddedCreatureTable
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.SerialColumn)
                .HasAnnotation("ProductVersion", "2.2.4-servicing-10062")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            modelBuilder.Entity("DeepSea.Creature", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("CountOfTimesSeen");

                    b.Property<float>("Elevation");

                    b.Property<string>("LocationOfLastSeen");

                    b.Property<int>("Population");

                    b.Property<int>("SizeInSquareMiles");

                    b.Property<string>("Species");

                    b.Property<bool>("Visited");

                    b.HasKey("Id");

                    b.ToTable("Creatures");
                });
#pragma warning restore 612, 618
        }
    }
}
